#!/bin/bash

Help() {
    echo "Usage: $0 <day_num> <task_name> <year>"
    echo "  day_num     Day number (e.g., 01, 02, ..., 25)"
    echo "  task_name   Task name (e.g., cube_conundrum, camp_cleanup etc.)"
    echo "  year        Year (e.g., 2022)"
}

# Check if the number of arguments is correct
if [ "$#" -ne 3 ]; then
    Help
    exit 1
fi

day_num="$1"
task_name="$2"
year="$3"

day_folder="year_$year/day_$day_num_$task_name"

cp -rv template "$day_folder"
jinja2 "$day_folder/solution.py.j2" -o "$day_folder/solution.py" -D "day_num=$day_num" -D "task_name=$task_name"
jinja2 "$day_folder/test.py.j2" -o "$day_folder/test.py" -D "day_num=$day_num" -D "task_name=$task_name"
rm -fv "$day_folder/solution.py.j2" "$day_folder/test.py.j2"
touch "$day_folder/input.txt"
touch "$day_folder/example.txt"