#!/bin/bash

Help() {
    echo "Usage: $0 <day_num> <task_name> <year> <language>"
    echo "  day_num     Day number (e.g., 01, 02, ..., 25)"
    echo "  task_name   Task name (e.g., cube_conundrum, camp_cleanup etc.)"
    echo "  year        Year (e.g., 2022)"
    echo "  language    Programming language (py or ts)"
}

# Check if the number of arguments is correct
if [ "$#" -ne 4 ]; then
    Help
    exit 1
fi

day_num="$1"
task_name="$2"
year="$3"
language="$4"

if [ "$language" == "py" ]; then
    year_folder="python/year_$year"
    day_folder="$year_folder/day_$day_num"_"$task_name"
elif [ "$language" == "ts" ]; then
    year_folder="typescript/year_$year"
    day_folder="$year_folder/day_$day_num"_"$task_name"
else
    echo "Unsupported language: $language"
    Help
    exit 1
fi

# Create the year folder if it doesn't exist
if [ ! -d "$year_folder" ]; then
    mkdir -p "$year_folder"
fi

mkdir -p "$day_folder"
touch "$day_folder/input.txt"
touch "$day_folder/example.txt"

if [ "$language" == "py" ]; then
    cp -rv python/template/* "$day_folder"
    jinja2 "$day_folder/solution.py.j2" -o "$day_folder/solution.py" -D "day_num=$day_num" -D "task_name=$task_name" -D"year=$year"
    jinja2 "$day_folder/test.py.j2" -o "$day_folder/test.py" -D "day_num=$day_num" -D "task_name=$task_name" -D"year=$year"
    rm -fv "$day_folder/solution.py.j2" "$day_folder/test.py.j2"
    
elif [ "$language" == "ts" ]; then
    cp -rv typescript/template/* "$day_folder"
    jinja2 "$day_folder/solution.ts.j2" -o "$day_folder/solution.ts" -D "day_num=$day_num" -D "task_name=$task_name" -D"year=$year"
    jinja2 "$day_folder/solution.spec.ts.j2" -o "$day_folder/solution.spec.ts" -D "day_num=$day_num" -D "task_name=$task_name" -D"year=$year"
    rm -fv "$day_folder/solution.ts.j2" "$day_folder/solution.spec.ts.j2"
else
    echo "Unsupported language: $language - Enter 'py' or 'ts'"
    Help
    exit 1
fi